version: 2.1
jobs:
  tests:
    docker:
      - image: ruby:3.0.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            gem install bundler -v 2.2.31
            bundle install
            bundle exec rake test
  lint:
    docker:
      - image: ruby:3.0.2
    steps:
      - checkout
      - run:
          name: Run lint
          command: |
            gem install bundler -v 2.2.31
            bundle install
            bundle exec rubocop

workflows:
  build_and_test:
    jobs:
      - tests
      - lint
