name: Create Linux release
on:
  push:
    tags:
      - 'v*.*.*'

env:
  RELEASE_VERSION: ${GITHUB_REF#refs/*/}

jobs:
  make:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Install Linux dependencies'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt install -y build-essential squashfs-tools curl gcc make bison
      - name: 'Install MacOs dependencies'
        if: matrix.os == 'macos-latest'
        run: |
          brew install squashfs
      - uses: actions/checkout@v2
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'
      - name: Set env
        run: |
          export LINUX_BIN_NAME=uffizzi-${{ env.RELEASE_VERSION }}-linux-x86_64
          export DARWIN_BIN_NAME=uffizzi-${{ env.RELEASE_VERSION }}-darwin-x86_64
      - name: 'Create Linux Bin'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          wget https://github.com/pmq20/ruby-packer/releases/download/linux-x64/rubyc
          chmod +x ./rubyc
          ./rubyc --openssl-dir=/etc/ssl ./uffizzi --output=LINUX_BIN_NAME
      - name: 'Create Darwin Bin'
        if: matrix.os == 'macos-latest'
        run: |
          wget https://github.com/pmq20/ruby-packer/releases/download/darwin-x64/rubyc
          chmod +x ./rubyc
          ./rubyc --openssl-dir=/etc/ssl ./uffizzi --output=DARWIN_BIN_NAME
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: LINUX_BIN_NAME
          path: LINUX_BIN_NAME
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: DARWIN_BIN_NAME
          path: DARWIN_BIN_NAME
  create_release:
    runs-on: ubuntu-latest
    needs:
      - make
    steps:
      - name: Download Linux Bin
        uses: actions/download-artifact@master
        with:
          name: LINUX_BIN_NAME
      - name: Download Macos Bin
        uses: actions/download-artifact@master
        with:
          name: DARWIN_BIN_NAME
      - name: Generate release notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          files: |
            ${{ github.workspace }}/LINUX_BIN_NAME
            ${{ github.workspace }}/DARWIN_BIN_NAME
          generate_release_notes: true
