name: Create Linux release
on:
  push:
    branches: [ feature/237_create_portable_binaries_2 ]
  pull_request:
    branches: [ feature/237_create_portable_binaries_2 ]
jobs:
  make:
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: "[Enclose.IO] Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential squashfs-tools curl
      - uses: actions/checkout@v2
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
      - name: "[Enclose.IO] Bundle install"
        run: bundle install
      - name: "[Enclose.IO] Create Linux Release"
        run: rake package:linux:x86_64 
