name: Create Linux release
on:
  push:
    tags:
      - 'test*.*.*'
env:
  RELEASE_VERSION: ${{ github.ref_name }}
  LINUX_BIN_PATH: uffizzi-linux
  DARWIN_BIN_PATH: uffizzi-darwin
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-binary:
    uses: ./.github/workflows/make-binary.yml
    secrets: inherit

